RAMCC/club/club/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_auth.views import LoginView, LogoutView, RegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include("music.urls", namespace='music')),
    path('news/', include("news.urls", namespace='news')),
    path('gallery/', include("gallery.urls", namespace='gallery')),
    path('', include("about.urls", namespace='about')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('captcha/', include('captcha.urls'))
    # path('adm/', include("dashboard.urls", namespace='dashboard'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)



#TODO
#1) Comments profile images out from user_profile_croped_img
#2) Make user_profile
#3) Make password show/hide on login, register form
#4) Make ajax calls for POST methods ar auth, comments ...
#5) Remove inline styles from templates to css files
#6) Oprimize background images load
#7) Normilize image (check for upload MB and sizes)
#8) Fix image not added when edit post
#9) Add not hardcoded status

RAMCC/club/news/urls.py
from django.contrib import admin
from django.urls import path
from .views import NewsList, NewsDetail, NewsCreate, NewsUpdate, NewsDelete, PostLikeToggle, CommentDelete
from .api import PostLikeAPIToggle, DashboardCounterAPI

app_name = 'news'
urlpatterns = [
    path('', NewsList.as_view(), name='post_list'),
    path('<slug:slug>', NewsDetail.as_view(), name='post_detail'),
    path('<slug:slug>/<int:id>/delete', CommentDelete.as_view(), name='comment_delete'),
    path('new/', NewsCreate.as_view(), name='post_create'),
    path('<slug:slug>/edit', NewsUpdate.as_view(), name='post_update'),
    path('<slug:slug>/delete', NewsDelete.as_view(), name='post_delete'),
    path('<int:id>/like', PostLikeToggle.as_view(), name='post_like'),

    path('api/<int:id>/like', PostLikeAPIToggle.as_view(), name='post_like_api'),
    path('api/events_count', DashboardCounterAPI.as_view(), name='dashboard_events')
]

RAMCC/club/news/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.contrib.contenttypes.models import ContentType
from comments.models import Comment


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(deleted__isnull=True, draft=True)

class Post(models.Model):
    title = models.CharField(max_length=120, blank=False, null=False)
    author = models.ForeignKey(User, blank=False, null=False, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    context = models.TextField(blank=False, null=False)
    updated = models.DateTimeField(auto_now=True, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    deleted = models.DateTimeField(blank=True, null=True)
    views = models.IntegerField(default=0, blank=True, null=False)
    draft = models.BooleanField(default=False, blank=True, null=False)
    published = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)

    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    image = models.ImageField(upload_to="news/posts/%Y/%m/%d", null=True, blank=True,
                              height_field="height_field",
                              width_field="width_field")

    likes = models.ManyToManyField(User, blank=True, related_name='post_likes')


    objects = PostManager()

    @property
    def is_deleted(self):
        if (self.deleted):
            return True
        return False

    @property
    def comments(self):
        instance = self
        comments = Comment.objects.filter_by_instance(instance).filter(parent=None, deleted__isnull=True)
        return comments

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    def view_counter(self):
        self.views += 1
        self.save()

    def set_deleted(self):
        if not (self.deleted):
            self.deleted = timezone.now()
            self.save()

    def get_absolute_url(self):
        return reverse("news:post_detail", kwargs={"slug": self.slug})

    def get_like_url(self):
        return reverse("news:post_like", kwargs={"id": self.id})

    def get_like_api_url(self):
        return reverse("news:post_like_api", kwargs={"id": self.id})

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)[:20]
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_resiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_resiver, sender=Post)

RAMCC/club/news/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "context",
            "image",
            "draft"
        ]
        widgets = {
            'image': forms.FileInput
        }

RAMCC/club/news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, RedirectView
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


from comments.forms import CommentForm
from comments.models import Comment
from .models import Post
from .forms import PostForm


# def anon_permissions(item, user):
#     if not user.is_authenticated


class NewsList(View):
    '''
    Returns news list for any user
    '''

    def get(self, request):
        search = request.GET.get('search')
        posts_list = Post.objects.active()  # Custom model manager see models.py
        if search:
            posts_list = posts_list.filter(
                Q(title__icontains=search) |
                Q(context__icontains=search) |
                Q(author__first_name__icontains=search)
            ).distinct()
        paginator = Paginator(posts_list, 5)
        page = request.GET.get('page')
        posts = paginator.get_page(page)
        return render(request, "post_list.html", {"posts": posts})


class NewsCreate(View):
    '''
    Returns post creation form and handle post creation
    '''
    @method_decorator(login_required)
    def get(self, request):
        if request.user.is_authenticated:
            form = PostForm()
            return render(request, "post_create.html", {"form": form})


    def post(self, request):
        form = PostForm(request.POST, request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, "Your post sended to draft")
            return redirect(post.get_absolute_url())
        return render(request, "post_create.html", {"form": form})


class NewsDetail(View):
    '''
    Return specific details about selected post with comments
    '''

    def get(self, request, slug=None):
        post = get_object_or_404(Post, slug=slug)
        if (post.deleted):
            raise Http404
        if (post.draft == False and request.user != post.author):
            raise Http404
        initial = {
            "content_type": post.get_content_type,
            "object_id": post.id
        }
        comment_form = CommentForm(request.POST or None, initial=initial)
        comments = post.comments
        post.view_counter()
        return render(request, "post_detail.html", {"detail": post,
                                                    "comments": comments,
                                                    "form": comment_form})

    def post(self, request, slug=None):
        print(request.body)
        print(request.POST)
        post = get_object_or_404(Post, slug=slug)
        initial = {
            "content_type": post.get_content_type,
            "object_id": post.id
        }
        comment_form = CommentForm(request.POST or None, initial=initial)
        if comment_form.is_valid():
            c_type = comment_form.cleaned_data.get("content_type")
            content_type = ContentType.objects.get(model=c_type)
            obj_id = comment_form.cleaned_data.get("object_id")
            content_data = comment_form.cleaned_data.get("content")
            parent_obj = None
            try:
                parent_id = request.POST.get("parent_id")
            except:
                parent_id = None
            if parent_id:
                parent_qs = Comment.objects.filter(id=parent_id)
                if parent_qs.exists():
                    parent_obj = parent_qs.first()

            new_comment, created = Comment.objects.get_or_create(user=request.user,
                                                                 content_type=content_type,
                                                                 object_id=obj_id,
                                                                 content=content_data,
                                                                 parent=parent_obj)
        return redirect(post.get_absolute_url())

class CommentDelete(View):
    '''
    Handle post comment delete
    '''
    #TODO
    #change method to post

    def get(self, request, slug, id=None):
        post = get_object_or_404(Post, slug=slug)
        comment = get_object_or_404(Comment, id=id)
        if request.user == comment.user or request.user.is_staff:
            comment.set_deleted()
            return redirect(post.get_absolute_url())
        response = HttpResponse("You cant delete other user comment")
        response.status_code = 403
        return response

class NewsUpdate(View):
    '''
    Handle editing chosen post
    '''

    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        if request.user != post.author:
            raise Http404
        form = PostForm(instance=post)
        context = {
            "post": post,
            "form": form
        }
        return render(request, "post_edit.html", context)

    def post(self, request, slug):
        if not request.user.is_authenticated:
            raise Http404
        post = get_object_or_404(Post, slug=slug)
        if request.user != post.author:
            raise Http404

        form = PostForm(request.POST or None, request.FILES or None, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.updated = timezone.now()
            post.save()
            messages.success(request, "Succesfully Updated!")
            return redirect(post.get_absolute_url())
        return render(request, "post_edit.html", {"form": form})


class NewsDelete(View):
    '''
    Handle deleting chosen post
    '''

    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        messages.success(request, "Successfully deleted!")
        post.set_deleted()
        return redirect("news:post_list")


class PostLikeToggle(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        id = self.kwargs.get("id")
        post = get_object_or_404(Post, id=id)
        url_ = post.get_absolute_url()
        user = self.request.user
        if user.is_authenticated:
            if user in post.likes.all():
                post.likes.remove(user)
            else:
                post.likes.add(user)
        return url_

RAMCC/club/news/templates/post_create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block title %}
    Create
{% endblock %}

{% block header %}
    {% include "header.html" %}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'news/css/create.css' %}">
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

{% block content %}
    <div class="wrap_content creation_form">
    <h1>Create new article:</h1>
        <hr>
        <div class="row justify-content-center">
            <div class="col-5 create_form">
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" value="Add"/>
            </div>
        </div>
    </div>
{% endblock %}

RAMCC/club/news/templates/post_detail.html
{% extends "base.html" %}
{% load octicons %}
{% load static %}
{% load crispy_forms_filters %}

{% block title %}
    {{ detail.title }}
{% endblock %}

{% block header %}
    {% include "header.html" %}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'news/css/detail.css' %}">
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

<script>
  {% block jquery %}
    const updateText = (btn, newCount, verb, counter) => {
      btn.attr("data-likes", newCount);
      btn.text(verb);
      counter.text(newCount);
    };

    $(".like-btn").click((e) => {
      e.preventDefault();
      let this_ = $(".like-btn");
      let likeURL = this_.attr("data-href");
      let likeCount = parseInt(this_.attr("data-likes"));
      let counter = $(".counter");
      $.ajax({
        url: likeURL,
        method: "GET"
      }).done((data) => {
        console.log(data);
        let newLike;
        if (data.liked) {
          let newLike = likeCount + 1;
          updateText(this_, newLike, "Unlike", counter);
        } else {
          let newLike = likeCount - 1;
          updateText(this_, newLike, "Like", counter);
        }
      }).fail((error) => {
        console.log(error);
        console.log("error");
      })
    });

    {#  Comments #}
    if ($(".comments").is(":hidden") === true) {
      $("#comments").val("Show comments")
    }
    else {
      $("#comments").val("Hide comments")
    }
    $("#comments").click(() => {
      if ($(".comments").is(":hidden") === true) {
        $(".comments").show();
        $("#comments").val("Hide comments");
      }
      else {
        $(".comments").hide();
        $("#comments").val("Show coments");
      }
    });

    elements = document.querySelectorAll(".reply");
    elements.forEach((el, i) => {
      const element = el;
      const id = element.getAttribute("data-id");
      $(".replies" + id).hide();
      element.onclick = () => {
        comment = $(".replies" + id);
        comment.toggle(500)
      }
    });
  {% endblock %}
</script>


{% block content %}
    {# Message section #}
    {% include "messages.html" %}


    {# Page content#}
    <div class="wrap_content">
        <div class="my_custom">
            {% if request.user.is_authenticated %}
                <a href="{% url 'news:post_update' slug=detail.slug %}" class="btn btn-light">Edit post</a>
            {% endif %}
            {% if request.user.is_staff or request.user == detail.author %}
                <a href="{% url 'news:post_delete' slug=detail.slug %}" class="btn btn-light">Delete post</a>
            {% endif %}
        </div>
        <hr>
        <div class="post-item">
            <div class="justify-content-center custom row">
                <div class="col-12">
                    <h1>{{ detail.title }}</h1>
                </div>
            </div>
            <hr>
            <div class="row oct-icons icon-counts">
                <div class="col-auto date">
                    <h3>Created {{ detail.created|timesince }} ago
                        by {% firstof detail.author.get_full_name detail.author %}</h3>
                </div>
                <div class="col-auto align-left">
                    {% octicon "eye" %} <h1>{{ detail.views }}</h1>
                </div>
                <div class="col align-left">
                    {% octicon "comment" %} <h1>{{ detail.comments.count }}</h1>
                </div>
                <div class="col-auto likes">
                    {% octicon "heart" %}
                    <span class="counter">{{ detail.likes.count }}</span>
                    <a class="like-btn btn btn-info"
                       data-href="{{ detail.get_like_api_url }}"
                       data-likes="{{ detail.likes.count }}"
                       href="{{ detail.get_like_url }}">Like</a>
                </div>
            </div>
            <hr>
            {% if detail.image %}
                <div class="row">
                    <div class="col text-center">
                        <img src="{{ detail.image.url }}" class="img-fluid image-item-detail"/>
                    </div>
                </div>
            {% endif %}
            <hr>
            <div class="text_area row">
                <div class="col-12">
                    <h3>{{ detail.context|linebreaks }}</h3>
                </div>
            </div>
        </div>
        <hr>
            <p class="com_text">Comments</p>
        <hr>
        {# Comments  #}
        {% if request.user.is_authenticated %}
            <div class="row justify-content-center">
                <div class="col-6">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Comment" class="btn btn-light btn_custom">
                    </form>
                </div>
            </div>
        {% else %}
            <p>You must <a href="{% url 'login' %}">login</a> first, to leave a comment.</p>
        {% endif %}
        {% if detail.comments.count != 0 %}
            <hr>
            <input type="submit" value="Show" id="comments" class="btn btn-light btn_toggler"/>
            <div class="comments">
                {% include "comments.html" %}
            </div>
        {% endif %}

    </div>
{% endblock %}

RAMCC/club/news/templates/post_edit.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block title %}
    Edit
{% endblock %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'news/css/edit.css' %}">
{% endblock %}


{% block header %}
    {% include "header.html" %}
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

{% block content %}
    <div class="wrap_content">
        <div class="row justify-content-center">
            <div class="col-5 form_edit">
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" value="Edit"/>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

RAMCC/club/news/templates/post_list.html
{% extends "base.html" %}
{% load static %}
{% load octicons %}

{% block title %}
    News
{% endblock %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'news/css/news.css' %}">
{% endblock %}


{% block header %}
    {% include "header.html" %}
{% endblock %}


{% block footer %}
    {% include 'footer.html' %}
{% endblock %}


{% block content %}
    <div class="wrap_content">
        {% include "messages.html" %}
        <form action="" method="GET">
            <div class="row my_custom">
                <div class="col">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'news:post_create' %}" class="btn btn-light">Create post</a>
                    {% else %}
                        <h3 class="anon_text">Log in to add post</h3>
                    {% endif %}
                </div>
                <div class="col-4">
                    <div class="input-group input">
                        <input class="form-control " type="text" name="search" placeholder="Search..."
                               value="{{ request.GET.search }}"/>
                        <button class="btn btn-light" type="submit">{% octicon "search" %}</button>
                    </div>
                </div>
            </div>
        </form>
        <hr>

        {# Post list #}
        {% for post in posts %}
            <div class="post_items">
                <div class="row">
                    <div class="col">
                        <a class="padd" href="{{ post.get_absolute_url }}">{{ post.title|capfirst }}</a>
                    </div>
                </div>
                <hr>
                <div class="row oct-icons justify-content-end icon-counts">
                    <div class="col date">
                       Created by {% firstof post.author.get_full_name post.author %} | {{ post.created|timesince }} ago
                    </div>
                    <div class="col-auto">
                        {% octicon "eye" %}  <h1>{{ post.views }}</h1>
                    </div>
                    <div class="col-auto">
                        {% octicon "comment" %}  <h1>{{ post.comments.count }}</h1>
                    </div>
                    <div class="col-auto align-right">
                        {% octicon "heart" %}  <h1>{{ post.likes.count }}</h1>
                    </div>
                </div>
                <hr>
                <div class="row">
                    {% if post.image %}
                        <div class="col-5 post-item-img-col">
                            <img src="{{ post.image.url }}" class="img-fluid post-img" alt="Responsive image"/>
                        </div>
                    {% endif %}
                    <div class="col text-justify post-item-text">
                        <h2>{{ post.context|linebreaks|truncatechars:300 }}</h2>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col text-right"><a href="{{ post.get_absolute_url }}">Read more ...</a></div>
                </div>
                <hr/>
            </div>
        {% empty %}
            <h1>Sorry no posts there</h1>
        {% endfor %}
        {% include "pagination.html" %}
    </div>
{% endblock %}