RAMCC/club/about/urls.py
from django.urls import path
from .views import AboutView


app_name = 'about'
urlpatterns = [
    path('', AboutView.as_view(), name='about_us'),
]

RAMCC/club/club/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_auth.views import LoginView, LogoutView, RegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include("music.urls", namespace='music')),
    path('news/', include("news.urls", namespace='news')),
    path('gallery/', include("gallery.urls", namespace='gallery')),
    path('', include("about.urls", namespace='about')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('captcha/', include('captcha.urls'))
    # path('adm/', include("dashboard.urls", namespace='dashboard'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)



#TODO
#1) Comments profile images out from user_profile_croped_img
#2) Make user_profile
#3) Make password show/hide on login, register form
#4) Make ajax calls for POST methods ar auth, comments ...
#5) Remove inline styles from templates to css files
#6) Oprimize background images load
#7) Normilize image (check for upload MB and sizes)
#8) Fix image not added when edit post
#9) Add not hardcoded status

RAMCC/club/gallery/urls.py
from django.urls import path
from .views import CreateGalleryAlbum, AddPhotos, GalleryAlbumView, GalleryHomeView

app_name = 'gallery'

urlpatterns = [
    path('create_gallery/', CreateGalleryAlbum.as_view(), name="create_gallery_album"),
    path('<slug:slug>/add_photos', AddPhotos.as_view(), name="add_photos"),
    path('<slug:slug>', GalleryAlbumView.as_view(), name="album_detail"),
    path('', GalleryHomeView.as_view(), name="gallery_home")

]

RAMCC/club/music/urls.py
from django.urls import path
from .views import CreateAlbum, CreateSong, SongDetail, AlbumDeleteView, MusicHomeView, DeleteSongView

app_name = 'music'

urlpatterns = [
    path('create_album/', CreateAlbum.as_view(), name="create_album"),
    path('<slug:slug>/add_song', CreateSong.as_view(), name="add_song"),
    path('<slug:slug>', SongDetail.as_view(), name="song_detail"),
    path('<slug:slug>/delete', AlbumDeleteView.as_view(), name="album_delete"),
    path('<slug:slug>/delete_song/<int:id>', DeleteSongView.as_view(), name="delete_song"),
    path('', MusicHomeView.as_view(), name="music_home")

]

RAMCC/club/news/urls.py
from django.contrib import admin
from django.urls import path
from .views import NewsList, NewsDetail, NewsCreate, NewsUpdate, NewsDelete, PostLikeToggle, CommentDelete
from .api import PostLikeAPIToggle, DashboardCounterAPI

app_name = 'news'
urlpatterns = [
    path('', NewsList.as_view(), name='post_list'),
    path('<slug:slug>', NewsDetail.as_view(), name='post_detail'),
    path('<slug:slug>/<int:id>/delete', CommentDelete.as_view(), name='comment_delete'),
    path('new/', NewsCreate.as_view(), name='post_create'),
    path('<slug:slug>/edit', NewsUpdate.as_view(), name='post_update'),
    path('<slug:slug>/delete', NewsDelete.as_view(), name='post_delete'),
    path('<int:id>/like', PostLikeToggle.as_view(), name='post_like'),

    path('api/<int:id>/like', PostLikeAPIToggle.as_view(), name='post_like_api'),
    path('api/events_count', DashboardCounterAPI.as_view(), name='dashboard_events')
]

RAMCC/club/comments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone


class CommentManager(models.Manager):
    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id)
        return qs

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)
    content = models.TextField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)
    deleted = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)

    objects = CommentManager()

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return str(self.user.username)


    def children(self): # Replies
        return Comment.objects.filter(parent=self)

    def set_deleted(self):
        if (self.deleted == None):
            self.deleted = timezone.now()
            self.save()

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

RAMCC/club/comments/forms.py
from django import forms


class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.CharField(widget=forms.HiddenInput)
    # parent_id = forms.CharField(widget=forms.HiddenInput, required=False)
    content = forms.CharField(label='', widget=forms.Textarea(attrs={'placeholder': 'Leave a comment here ...'}))

RAMCC/club/comments/views.py
from django.shortcuts import render

# Create your views here.

RAMCC/club/club/templates/base.html
{% load static %}
{% load octicons %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {# Styles #}
    {% include 'styles.html' %}
    {% block styles %}
    {% endblock %}
</head>

<body>
<div class="container">
    {# Header #}
    {% block header %}
    {% endblock %}
    <br>
    {# Content #}
    {% block content %}
    {% endblock %}
    {# Footer #}
    {% block footer %}
    {% endblock %}

    {# Scripts#}
    {% include 'js.html' %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/header.js' %}"></script>
    <script>
      $('.logo').hide();
      $(document).ready(() => {
        {% block jquery %}{% endblock %}

        $(".menu-icon").on("click", function () {
          $("nav ul").toggleClass("showing");
        });

        // Scrolling Effect
        $(window).on("scroll", function () {
          if ($(window).scrollTop()) {
            $('nav').addClass('black');
            $('.logo').show();
          }
          else {
            $('nav').removeClass('black');
            $('.logo').hide();
          }

        })
      })
    </script>
</div>
</body>
</html>

RAMCC/club/club/templates/comments.html
{% load crispy_forms_filters %}
{% load octicons %}
<div class="row">
    <div class="col-12 content_section">
    <p>Comments: </p>
        {% for comment in comments %}
            <blockquote class="blockquote">
                <p class="mb-0">{{ comment.content }}</p>
                <footer class="blockquote-footer">{% firstof comment.user.get_full_name comment.user %}
                    | {{ comment.created|timesince }} ago | <span class="reply"
                                                                  data-id="{{ comment.id }}"> {% octicon "reply" %} Reply </span>
                </footer>
            {% if request.user.is_staff or request.user == comment.user%}
                <a class="btn btn-light float-right" href="{% url 'news:comment_delete' slug=detail.slug id=comment.id %}">{% octicon "trashcan" %}</a>
                <br>
            {% endif %}
                {% for chield in comment.children %}
                    <blockquote class="blockquote reply">
                        <p class="mb-0">{{ chield.content }}</p>
                        <footer class="blockquote-footer">{% firstof chield.user.get_full_name chield.user %}
                            | {{ chield.created|timesince }} ago
                        </footer>
                    </blockquote>
                {% endfor %}
                <div class="replies{{ comment.id }}">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="hidden" name="parent_id" value="{{ comment.id }}">
                        <input type="submit" value="Send" class="btn btn-dark">
                    </form>
                </div>
            </blockquote>
            <hr>
        {% endfor %}
    </div>
</div>

RAMCC/club/club/templates/footer.html
{% load static %}
{% load octicons %}
<div class="row footer">
    <div class="col text-left">
        <img src="{% static 'club/images/logo_white.png' %}" alt=""><h3>RAMCC</h3>
    </div>
    <div class="col-auto">
        <h5>© All rights reserved</h5>
    </div>
    <div class="col text-right">
        <h5>+0937706498 {% octicon "device-mobile" %}<br>+0631935823 {% octicon "device-mobile" %}</h5>
    </div>
</div>

RAMCC/club/club/templates/header.html
{% load static %}
<div class="wrapper">
    <header>
        <div>
            {% if request.user.is_superuser %}
                <div class="dash">
                    <div class="event_counts">
                        <a href="#" data-href="{% url 'news:dashboard_events' %}" class="btn btn-light events">
                            <span class="btn__badge" id="tst"> </span>
                            Dashboard</a>
                    </div>
                </div>
            {% endif %}
            <h1 class="text-header">
                <div class="row">
                    <div class="col-8"><h3>Welcome
                        {% if request.user.get_full_name %}{{ request.user.get_full_name|capfirst }}{% endif %} at
                        Reckless Angels MCC page</h3></div>
                    <div class="col"><img class="pull-right img-responsive"
                                          src="{% static 'club/images/logo_white.png' %}"></div>
                </div>
            </h1>
        </div>
        <nav>
            <div class="menu-icon">
                <i class="fa fa-bars fa-2x"></i>
            </div>
            <div class="logo">
                <div class="row">
                    <img src="{% static 'club/images/logo_white.png' %}" alt="" class="logo-img">
                    <h3 class="header-title">Reckless <br> Angels MCC</h3>
                </div>
            </div>
            <div class="menu">
                <ul>
                    <li><a href="{% url 'news:post_list' %}">News</a></li>
                    <li><a href="{% url 'about:about_us' %}">About us</a></li>
                    <li><a href="{% url 'gallery:gallery_home' %}">Gallery</a></li>
                    <li><a href="{% url 'music:music_home' %}">Music</a></li>
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
</div>

RAMCC/club/club/templates/js.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

RAMCC/club/club/templates/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

RAMCC/club/club/templates/pagination.html
{% if posts %}
    <div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ posts.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}&search={{ request.GET.search }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">next</a>
            <a href="?page={{ posts.paginator.num_pages }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}&search={{ request.GET.search }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
{% endif %}

RAMCC/club/club/templates/permissions.html
{% extends 'base.html' %}

{% block title %}
    Not allowed
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}


{% block content %}
    <h1>You shoud <a href="{% url 'login' %}">login</a> first.</h1>
{% endblock %}

RAMCC/club/club/templates/styles.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href='{% static "news/css/base.css" %}'>
<link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
<link rel="stylesheet" href="{% static "club/css/header.css" %}">
<link rel="stylesheet" href="{% static "club/css/footer.css" %}">
<link href="https://fonts.googleapis.com/css?family=Black+Ops+One" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
<link rel="stylesheet" href="{% static "club/css/base.css" %}">
<link href="https://fonts.googleapis.com/css?family=Ranga" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Cormorant" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Unlock" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">