RAMCC/club/club/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_auth.views import LoginView, LogoutView, RegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include("music.urls", namespace='music')),
    path('news/', include("news.urls", namespace='news')),
    path('gallery/', include("gallery.urls", namespace='gallery')),
    path('', include("about.urls", namespace='about')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('captcha/', include('captcha.urls'))
    # path('adm/', include("dashboard.urls", namespace='dashboard'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)



#TODO
#1) Comments profile images out from user_profile_croped_img
#2) Make user_profile
#3) Make password show/hide on login, register form
#4) Make ajax calls for POST methods ar auth, comments ...
#5) Remove inline styles from templates to css files
#6) Oprimize background images load
#7) Normilize image (check for upload MB and sizes)
#8) Fix image not added when edit post
#9) Add not hardcoded status

RAMCC/club/gallery/urls.py
from django.urls import path
from .views import CreateGalleryAlbum, AddPhotos, GalleryAlbumView, GalleryHomeView

app_name = 'gallery'

urlpatterns = [
    path('create_gallery/', CreateGalleryAlbum.as_view(), name="create_gallery_album"),
    path('<slug:slug>/add_photos', AddPhotos.as_view(), name="add_photos"),
    path('<slug:slug>', GalleryAlbumView.as_view(), name="album_detail"),
    path('', GalleryHomeView.as_view(), name="gallery_home")

]

RAMCC/club/gallery/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import Permission, User
from django.db.models.signals import pre_save
from django.urls import reverse


class GalleryAlbum(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    album_title = models.CharField(max_length=200, null=False, blank=False)
    album_logo = models.FileField(upload_to="gallery/albums_logo_gallery")
    slug = models.SlugField(unique=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title

    def get_absolute_url(self):
        return reverse("gallery:album_detail", kwargs={"slug": self.slug})

    @property
    def is_deleted(self):
        if (self.deleted):
            return True
        return False


class Photo(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    album = models.ForeignKey(GalleryAlbum, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)
    image_file = models.FileField(default='', upload_to="gallery/photos")
    is_favorite = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.image_file

    @property
    def is_deleted(self):
        if (self.deleted):
            return True
        return False


def create_slug(instance, new_slug=None):
    slug = slugify(instance.album_title)[:20]
    if new_slug is not None:
        slug = new_slug
    qs = GalleryAlbum.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_resiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_resiver, sender=GalleryAlbum)

RAMCC/club/gallery/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import GalleryAlbum, Photo


class GalleryAlbumForm(forms.ModelForm):
    class Meta:
        model = GalleryAlbum
        fields = ['album_title', 'album_logo']


class PhotoForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ['image_file']

RAMCC/club/gallery/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, RedirectView
from django.db.models import Q
from django.http import Http404
from .models import GalleryAlbum, Photo
from .forms import GalleryAlbumForm, PhotoForm

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


class CreateGalleryAlbum(View):

    def get(self, request):
        if request.user.is_anonymous:
            return render(request, 'permissions.html', status=403)
        form = GalleryAlbumForm()
        context = {
            "form": form
        }
        return render(request, 'gallery/create_gallery_album.html', context)

    def post(self, request):
        if request.user.is_anonymous:
            return render(request, 'permissions.html', status=403)
        form = GalleryAlbumForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            album.album_logo = request.FILES['album_logo']
            file_type = album.album_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'gallery/create_gallery_album.html', context)
            album.save()
            return redirect(album.get_absolute_url())
        return render(request, 'gallery/create_gallery_album.html', {"form": form})


class AddPhotos(View):

    def get(self, request, slug):
        if request.user.is_anonymous:
            return render(request, 'permissions.html', status=403)
        form = PhotoForm()
        album = get_object_or_404(GalleryAlbum, slug=slug)
        return render(request, 'gallery/add_photo.html', {"form": form, "album": album})

    def post(self, request, slug):
        if request.user.is_anonymous:
            return render(request, 'permissions.html', status=403)
        form = PhotoForm(request.POST or None, request.FILES or None)
        album = get_object_or_404(GalleryAlbum, slug=slug)
        photos = Photo.objects.filter(album=album)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.album = album
            photo.owner = request.user
            photo.image_file = request.FILES['image_file']
            file_type = photo.image_file.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'gallery/add_photo.html', context)
            photo.save()
        return redirect(album.get_absolute_url())


class GalleryAlbumView(View):

    def get(self, request, slug):
        if request.user.is_anonymous:
            return render(request, 'permissions.html', status=403)
        user = request.user
        album = get_object_or_404(GalleryAlbum, slug=slug)
        photos = Photo.objects.filter(album=album)
        return render(request, 'gallery/album_detail.html', {'album': album, 'user': user, 'photos': photos})


class GalleryHomeView(View):

    def get(self, request):
        albums = GalleryAlbum.objects.filter(deleted=False)
        return render(request, 'gallery/index.html', {"albums": albums})

RAMCC/club/gallery/templates/gallery/add_photo.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %}
    Add photos
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

{% block styles %}
{% endblock %}

<script>
  {% block jquery %}
    var loadFile = function (event) {
      var output = document.getElementById('output');
      output.src = URL.createObjectURL(event.target.files[0]);
    };
  {% endblock %}
</script>


{% block content %}
    <div class="wrap_content">
        <h1>Add photos to album:</h1>
        <hr>
        <div class="row justify-content-center">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="album" value="{{ album }}">
                {{ form|crispy }}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

RAMCC/club/gallery/templates/gallery/album_detail.html
{% extends 'base.html' %}
{% load static %}
{% load octicons %}

{% block title %}
    {{ album.album_title }}
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

<script>
  {% block jquery %}
    elements = document.querySelectorAll(".pop");
    elements.forEach((el, i) => {
      const element = el;
      const src = element.getAttribute("src");
      element.onclick = () => {
        $(".output").attr('src', src)
      }
    });

  {% endblock %}
</script>

{% block styles %}
    <link rel="stylesheet" href="{% static 'gallery/css/detail.css' %}">
{% endblock %}

{% block content %}
    <div class="wrap_content gallery_images">
        <h1>{{ album.album_title }}</h1>
        <hr>
        <div class="row">
            <a class="btn btn-dark" href="{% url 'gallery:add_photos' album.slug %}">Add photos</a>
        </div>
        <hr>
        <ul class="list-inline check">
            {% for photo in photos %}
                <li class="list-inline-item" data-toggle="modal" data-target="#myModal"
                    data-slide-to="{{ album.id }}">
                    <img class="img-thumbnail img-items pop" src="{{ photo.image_file.url }}"
                         data-id={{ photo.id }}><br>
                </li>
                {#                <div class="card img-items" style="width: 17rem;">#}
                {#                    <img class="card-img-top" src="{{ photo.image_file.url }}" alt="Card image cap">#}
                {#                </div>#}
            {% empty %}
                <h3>No images yet</h3>
            {% endfor %}
        </ul>
        <div class="modal fade" id="myModal">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="pull-left"><h1>{{ album.album_title }}</h1></div>
                    </div>
                    <div class="modal-body">
                        <div id="myGallery" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img class="output img-responsive" src="">
                                </div>
                                {% for photo in photos %}
                                    <div class="carousel-item"><img src="{{ photo.image_file.url }}"
                                                                    alt="item{{ photo.id }}">
                                    </div>
                                {% endfor %}
                                <!--end carousel-inner--></div>
                            <!--Begin Previous and Next buttons-->
                            <a class="carousel-control-prev" href="#myGallery" role="button"
                               data-slide="prev">
                                {% octicon "triangle-left" %}
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#myGallery" role="button"
                               data-slide="next">
                                {% octicon "triangle-right" %}
                                <span class="sr-only">Next</span>
                            </a>
                            <!--end carousel--></div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn-sm close" type="button" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

RAMCC/club/gallery/templates/gallery/create_gallery_album.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}


{% block title %}
    Add album
{% endblock %}


{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'gallery/css/create_album.css' %}">
{% endblock %}

{% block content %}
    <div class="wrap_content">
        <div class="row justify-content-center create_album">
            <div class="col-12"><h3>Add new album:</h3></div>
            <hr>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            <div class="col-6">
                <form class="form-horizontal create_form" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

RAMCC/club/gallery/templates/gallery/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Albums
{% endblock %}

{% block header %}
    {% include "header.html" %}
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'gallery/css/index.css' %}">
{% endblock %}


{% block content %}
    <div class="wrap_content">
        <div class="row">
            <div class="col-12">
                <h3>Albums</h3>
                <hr>
                <a href="{% url 'gallery:create_gallery_album' %}" class="btn btn-dark">Create album</a>
                <hr>
            </div>
            {% if albums %}
                {% for album in albums %}
                    <div class="col-4">
                        <div class="thumbnail album_item">
                            <div class="album_img">
                                <a href="{% url 'gallery:album_detail' album.slug %}">
                                    <img src="{{ album.album_logo.url }}" class="img-responsive">
                                </a>
                            </div>
                            <div class="caption">
                                <hr>
                                <h2>{{ album.album_title }}</h2>

                            </div>
                        </div>
                    </div>
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                {% endfor %}
            {% else %}
                <h1>No albums yet</h1>
            {% endif %}
        </div>
    </div>
{% endblock %}