RAMCC/club/club/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_auth.views import LoginView, LogoutView, RegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include("music.urls", namespace='music')),
    path('news/', include("news.urls", namespace='news')),
    path('gallery/', include("gallery.urls", namespace='gallery')),
    path('', include("about.urls", namespace='about')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('captcha/', include('captcha.urls'))
    # path('adm/', include("dashboard.urls", namespace='dashboard'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)



#TODO
#1) Comments profile images out from user_profile_croped_img
#2) Make user_profile
#3) Make password show/hide on login, register form
#4) Make ajax calls for POST methods ar auth, comments ...
#5) Remove inline styles from templates to css files
#6) Oprimize background images load
#7) Normilize image (check for upload MB and sizes)
#8) Fix image not added when edit post
#9) Add not hardcoded status

RAMCC/club/music/urls.py
from django.urls import path
from .views import CreateAlbum, CreateSong, SongDetail, AlbumDeleteView, MusicHomeView, DeleteSongView

app_name = 'music'

urlpatterns = [
    path('create_album/', CreateAlbum.as_view(), name="create_album"),
    path('<slug:slug>/add_song', CreateSong.as_view(), name="add_song"),
    path('<slug:slug>', SongDetail.as_view(), name="song_detail"),
    path('<slug:slug>/delete', AlbumDeleteView.as_view(), name="album_delete"),
    path('<slug:slug>/delete_song/<int:id>', DeleteSongView.as_view(), name="delete_song"),
    path('', MusicHomeView.as_view(), name="music_home")

]

RAMCC/club/music/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import Permission, User
from django.db.models.signals import pre_save
from django.urls import reverse


class MusicAlbum(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    artist = models.CharField(max_length=200, null=True, blank=True)
    album_title = models.CharField(max_length=200, null=False, blank=False)
    genre = models.CharField(max_length=100, null=True, blank=True)
    album_logo = models.FileField(upload_to="albums_logo")
    is_favorite = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title

    def get_absolute_url(self):
        return reverse("music:song_detail", kwargs={"slug": self.slug})

    @property
    def is_deleted(self):
        if (self.deleted):
            return True
        return False


class Song(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    album = models.ForeignKey(MusicAlbum, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='', upload_to="music/songs")
    is_favorite = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

    @property
    def is_deleted(self):
        if (self.deleted):
            return True
        return False


def create_slug(instance, new_slug=None):
    slug = slugify(instance.album_title)[:20]
    if new_slug is not None:
        slug = new_slug
    qs = MusicAlbum.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_resiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_resiver, sender=MusicAlbum)

RAMCC/club/music/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import MusicAlbum, Song


class AlbumForm(forms.ModelForm):
    class Meta:
        model = MusicAlbum
        fields = ['artist', 'album_title', 'genre', 'album_logo']


class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['song_title', 'audio_file']

RAMCC/club/music/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, RedirectView
from .forms import AlbumForm, SongForm
from .models import MusicAlbum, Song
from django.db.models import Q
from django.http import Http404

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


class CreateAlbum(View):

    def get(self, request):
        if request.user.is_anonymous:
            return render(request, 'permissions.html', status=403)
        form = AlbumForm()
        context = {
            "form": form
        }
        return render(request, 'music/create_album.html', context)

    def post(self, request):
        if request.user.is_anonymous:
            return render(request, 'permissions.html', status=403)
        form = AlbumForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            album.album_logo = request.FILES['album_logo']
            file_type = album.album_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'music/create_album.html', context)
            if album.artist == None:
                album.artist = "Mixed"
            album.save()
            return render(request, 'music/detail.html', {"album": album})
        return render(request, 'music/create_album.html', {"form": form})


class CreateSong(View):

    def get(self, request, slug):
        if request.user.is_anonymous:
            return render(request, 'permissions.html', status=403)
        form = SongForm()
        album = get_object_or_404(MusicAlbum, slug=slug)
        return render(request, 'music/add_song.html', {"form": form, "album": album})

    def post(self, request, slug):
        if request.user.is_anonymous:
            return render(request, 'permissions.html', status=403)
        form = SongForm(request.POST or None, request.FILES or None)
        album = get_object_or_404(MusicAlbum, slug=slug)
        if form.is_valid():
            album_songs = album.song_set.all()
            for song in album_songs:
                if song.song_title == form.cleaned_data.get("song_title"):
                    context = {
                        'album': album,
                        'form': form,
                        'error_message': 'You already added that song',
                    }
                    return render(request, 'music/add_song.html', context)
            song = form.save(commit=False)
            song.album = album
            song.owner = request.user
            song.audio_file = request.FILES['audio_file']
            file_type = song.audio_file.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in AUDIO_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Audio file must be WAV, MP3, or OGG',
                }
                return render(request, 'music/add_song.html', context)
            song.save()
        return render(request, 'music/detail.html', {'album': album})


class SongDetail(View):

    def get(self, request, slug):
        if request.user.is_anonymous:
            return render(request, 'permissions.html', status=403)
        user = request.user
        album = get_object_or_404(MusicAlbum, slug=slug)
        return render(request, 'music/detail.html', {'album': album, 'user': user})


class AlbumDeleteView(View):

    def post(self, request, slug):
        if request.user.is_staff:
            album = get_object_or_404(MusicAlbum, slug=slug)
            album.deleted = True
            album.save()
            albums = MusicAlbum.objects.filter(deleted=False)
            return render(request, 'music/music_index.html', {"albums": albums})
        raise Http404

class MusicHomeView(View):

    def get(self, request):
        albums = MusicAlbum.objects.filter(deleted=False)
        song_results = Song.objects.all()
        query = request.GET.get("q")
        if query:
            albums = albums.filter(
                Q(album_title__icontains=query) |
                Q(artist__icontains=query)
            ).distinct()
            song_results = song_results.filter(
                Q(song_title__icontains=query)
            ).distinct()
            return render(request, 'music/music_index.html', {"albums": albums,
                                                              "songs": song_results})
        else:
            return render(request, 'music/music_index.html', {"albums": albums})


class DeleteSongView(View):

        def post(self, request, slug, id):
            if request.user.is_anonymous:
                raise Http404
            album = get_object_or_404(MusicAlbum, slug=slug)
            song = get_object_or_404(Song, pk=id)
            song.delete()
            return redirect(album.get_absolute_url())

    

RAMCC/club/music/templates/music/add_song.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %}
    Add song
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'music/css/add_song.css' %}">
{% endblock %}

{% block content %}
    <div class="row">
         <div class="col-5 album_img">
            <a href="{% url 'music:song_detail' album.slug %}">
                {% if album.album_logo %}
                    <img src="{{ album.album_logo.url }}" class="img-responsive">
                {% else %}
                    <h3>No image to display</h3>
                {% endif %}
            </a>
            <h1>{{ album.album_title }}
            </h1>
        </div>
        {# Right side #}
        <div class="col">
           <ul class="nav nav-pills">
                <li role="presentation" class="active"><a href="{% url 'music:song_detail' album.slug %}">View All</a>
                </li>
                <pre> </pre><li role="presentation"><a href="{% url 'music:add_song' album.slug %}">Add New Song</a></li>
            </ul>
            <hr>
            <div class="list">
                <h3>Add Song</h3>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            <form class="form-horizontal add_song" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="album" value="{{ album }}">
                {{ form|crispy }}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>
{% endblock %}

RAMCC/club/music/templates/music/create_album.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}


{% block title %}
    Add album
{% endblock %}


{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

{% block content %}
    <div class="wrap_content">
    <div class="row justify-content-center">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Add new album:</h3>
                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
    </div>
{% endblock %}

RAMCC/club/music/templates/music/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ album.album_title }}
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'music/css/music_detail.css' %}">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-5 album_img">
            <a href="{% url 'music:song_detail' album.slug %}">
                {% if album.album_logo %}
                    <img src="{{ album.album_logo.url }}" class="img-responsive">
                {% else %}
                    <h3>No image to display</h3>
                {% endif %}
            </a>
            <h1>{{ album.album_title }}
            </h1>
        </div>
        <div class="col">
            <ul class="nav nav-pills">
                <li role="presentation" class="active"><a href="{% url 'music:song_detail' album.slug %}">View All</a>
                </li>
                <pre> </pre><li role="presentation"><a href="{% url 'music:add_song' album.slug %}">Add New Song</a></li>
            </ul>
            <hr>
            <div class="list">
                <h3>All Songs</h3>
                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <table class="table">
                    <thead>
                    <tr>
                        <th id="th_title">Title</th>
                        <th id="th_file">Audio File</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                </table>
                {% for song in album.song_set.all %}
                    <table class="table songs-table">
                    <tr>
                        <td id="song-title">{{ song.song_title }}</td>
                        <td>
                            <a target="_blank" href="{{ song.audio_file.url }}">
                                <button type="button" class="btn btn-success btn-xs">Play
                                </button>
                            </a>
                        </td>
                        <td>
                            <form action="{% url 'music:delete_song' album.slug song.id %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="song_id" value="{{ song.id }}"/>
                                <button type="submit" class="btn btn-danger btn-xs">Delete
                                </button>
                            </form>
                        </td>
                    </tr>
                    </table>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

RAMCC/club/music/templates/music/music_index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Albums
{% endblock %}

{% block header %}
    {% include "header.html" %}
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'music/css/music_index.css' %}">
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-12">
            <h3>Albums</h3>
            <hr>
            <a href="{% url 'music:create_album' %}" class="btn btn-dark">Create album</a>
            <hr>
        </div>
        {% if albums %}
            {% for album in albums %}
                <div class="col-4">
                    <div class="thumbnail album_item">
                        <div class="album_img">
                            <a href="{% url 'music:song_detail' album.slug %}">
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            </a>
                        </div>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>Artist:{{ album.artist }}</h4>
                            <h4>Genre: {{ album.genre }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:song_detail' album.slug %}" class="btn btn-primary btn-sm"
                               role="button">View
                                Details</a>

                            <!-- Delete Album -->
                            {% if request.user.is_authenticated or reqeust.user.is_staff and request.user == album.user %}
                            <form action="{% url 'music:album_delete' album.slug %}" method="post"
                                  style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.slug }}"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                    Delete
                                </button>
                            </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <h1>No albums yet</h1>
        {% endif %}
    </div>
{% endblock %}